# Generated by Django 4.2.16 on 2024-09-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skillset',
        ),
    ]
